@startuml
|Аналітик|
    start
    :Вибирає відповідне опитування;
    |Система|
    :Пропонує інструменти для \nперегляду результатів анкетування анкети;
    |Аналітик|
    :За бажанням користується інструментами \nдля формування звіту;
    :Натискає кнопку \n"Сформувати звіт";
    |Система|
    :Аналізує і надсилає результати;
    |Аналітик|
    :Натискає кнопку \n"Закрити анкетування";
    |Система|
    :Видаляє анкети зі списку доступних;
    |Аналітик|
    stop
@enduml