@startuml
entity User
  entity User.id
  entity User.username
  entity User.data

  entity Expert
  entity Expert.id
  entity Expert.occupation


  entity Survey
  entity Survey.id
  entity Survey.name
  entity Survey.topic

  entity Question
  entity Question.id
  entity Question.type
  entity Question.text

  entity Answer
  entity Answer.id
  entity Answer.text

  entity PossibleAnswers
  entity PossibleAnswers.id
  entity PossibleAnswers.text



  User.id -u-* User
  User.username -u-* User
  User.role -u-* User

  Expert.id -u-* Expert
  Expert.occupation -u-* Expert


  Question "0, *" -u- "1, 1" Survey
  Expert "1, 1" -u- "0, 1" Answer
  User "0, *" -u- "1, 1" Question
  Answer "0, *" -d- "1, 1" User
  PossibleAnswers "0, *" -u- "1, 1" Question

  Survey.id -d-* Survey
  Survey.name -d-* Survey
  Survey.topic -d-* Survey
  Survey.deadline -d-* Survey

  Question.id -u-* Question
  Question.type -u-* Question
  Question.text -u-* Question

  Answer.id -u-* Answer
  Answer.date -u-* Answer
  Answer.text -u-* Answer

  PossibleAnswers.id -u-* PossibleAnswers
  PossibleAnswers.text -u-* PossibleAnswers
@enduml