@startuml
right header
<font size=24 color=black>Package: <b>UCD_1.1
end header

title
<font size=18 color=black>Сервіс анкетувань Survegana
<font size=16 color=black>Модель прецедентів
end title

actor "Респондент" as User
actor "Аналітик" as Analyst
actor "Замовник" as Customer
actor "Менеджер" as Manager

' UCes for User:
usecase "<b>UC_1</b>\nРедагування даних\nреспондента" as UC1_User
usecase "<b>UC_2</b>\nЗаповнення опитувань" as UC2_User

' UCes for Analyst:
usecase "<b>UC_1</b>\nПерегляд результатів\nопитувань" as UC1_Analyst
usecase "<b>UC_2</b>\nВикористання інструментів\nдля формування звітності" as UC2_Analyst
usecase "<b>UC_3</b>\nСтворення опитувань" as UC3_Analyst

' UCes for Customer:
usecase "<b>UC_1</b>\nПерегляд результатів опитування" as UC1_Customer


' UCes for Manager:
usecase "<b>UC_1</b>\nАвтоматизована передача анкет\nвід респондентів до інтерв’юерів" as UC1_Manager
usecase "<b>UC_2</b>\nДоступ до можливостей та прав інтерв’юера\nта аналітика" as UC2_Manager

' Actors connections


Manager -u--|> User

User -u-> UC1_User
User -u-> UC2_User

Analyst -r-> UC1_Analyst
Analyst -d-> UC2_Analyst
Analyst -u-> UC1_Customer
Analyst -d-> UC3_Analyst
Customer -u-> UC1_Customer


Manager -d--> UC1_Manager
Manager -d-> UC2_Manager

right footer
Survegana poll system. Модель прецедентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml