@startuml
|Аналітик|
    start
    :Натискає кнопку \n«Створити нове опитування»;
    |Система|
    :Пропонує інструменти для \nстворення анкети;
    |Аналітик|
    :Формує питання анкети \n(альтернативні, з кількома відповідями, оціночні, \nза шкалою Лайкерта);
    :Натискає кнопку \n"Завершити створення анкети";
    |Система|
    :Пропонує переглянути створену анкету;
    |Аналітик|
    :Перевіряє анкету;
    :Натискає кнопку \n"Зберегти анкету";
    |Система|
    :Перевіряє введені \nдані;
    :Зберігає анкету;
    |Аналітик|
    stop
@enduml