@startuml
|Респондент|
    start
    :Натискає кнопку \n«Розпочати опитування»;
    |Система|
    :Надає анкету для \nпроходження опитування;
    |Респондент|
    :Відповідає на питання анкети\n(альтернативні, з кількома відповідями, оціночні, \nза шкалою Лайкерта);
    :Натискає кнопку \n"Завершити";
    |Система|
    :Пропонує переглянути результати;
    |Респондент|
    :Натискає кнопку \n"Зберегти результати";
    |Система|
    :Зберігає результати;
    |Респондент|
    stop
@enduml