@startuml
|Користувач|
    start
    :Натискає кнопку \n«Sign Up»;
    |Система|
    :Пропонує форму \nдля початку реєстрації;
    |Користувач|
    :Заповнює поле: \nтип користувача;
    |Система|
    :Пропонує відповідну форму для реєстрації;
    |Користувач|
    :Заповнює поле: логін. пароль\nemail і тд.;
    |Система|
    :Перевіряє введені \nдані;
    :Зберігає дані;
    :Надає доступ до \nакаунту;
    |Користувач|
    stop
@enduml