@startuml
|Користувач|
    start
    :Натискає кнопку \n«Sign In»;
    |Система|
    :Пропонує форму \nдля входу в систему»;
    |Користувач|
    :Заповнює поля: \nemail, пароль;
    |Система|
    :Перевіряє введені \nдані;
    :Надсилає код для входу;
    |Користувач|
    :Заповнює поле: код;
    |Система|
    :Перевіряє введені \nдані;
    :Надає доступ до \nакаунту;
    |Користувач|
    stop
@enduml